// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WardenData.Models;

#nullable disable

namespace WardenData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250912212608_InitialNormalizedSchema")]
    partial class InitialNormalizedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WardenData.Models.Effect", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_percent");

                    b.Property<int?>("MaxPossible")
                        .HasColumnType("integer")
                        .HasColumnName("max_possible");

                    b.Property<int?>("MinPossible")
                        .HasColumnType("integer")
                        .HasColumnName("min_possible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_effects_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_effects_name");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("WardenData.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("original_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_name");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WardenData.Models.OrderEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("DesiredValue")
                        .HasColumnType("bigint")
                        .HasColumnName("desired_value");

                    b.Property<short>("EffectId")
                        .HasColumnType("smallint")
                        .HasColumnName("effect_id");

                    b.Property<long>("MaxValue")
                        .HasColumnType("bigint")
                        .HasColumnName("max_value");

                    b.Property<long>("MinValue")
                        .HasColumnType("bigint")
                        .HasColumnName("min_value");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("original_id");

                    b.HasKey("Id");

                    b.HasIndex("EffectId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderEffects");
                });

            modelBuilder.Entity("WardenData.Models.Rune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Runes");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<bool>("HasSucceed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_succeed");

                    b.Property<bool>("IsTenta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tenta");

                    b.Property<int>("OriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("original_id");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer")
                        .HasColumnName("rune_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("ix_rune_histories_applied_at");

                    b.HasIndex("RuneId");

                    b.HasIndex("SessionId", "OriginalId")
                        .IsUnique()
                        .HasDatabaseName("uq_rh_session_step");

                    b.ToTable("RuneHistories");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistoryEffectChange", b =>
                {
                    b.Property<Guid>("RuneHistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("rune_history_id");

                    b.Property<short>("EffectId")
                        .HasColumnType("smallint")
                        .HasColumnName("effect_id");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer")
                        .HasColumnName("new_value");

                    b.Property<int?>("OldValue")
                        .HasColumnType("integer")
                        .HasColumnName("old_value");

                    b.HasKey("RuneHistoryId", "EffectId");

                    b.HasIndex("EffectId", "RuneHistoryId")
                        .HasDatabaseName("ix_rhec_effect");

                    b.ToTable("RuneHistoryEffectChanges");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("OriginalId")
                        .HasColumnType("integer")
                        .HasColumnName("original_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_sessions_started_at");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WardenData.Models.SessionInitialEffect", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<short>("EffectId")
                        .HasColumnType("smallint")
                        .HasColumnName("effect_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("SessionId", "EffectId");

                    b.HasIndex("EffectId")
                        .HasDatabaseName("ix_sie_effect");

                    b.ToTable("SessionInitialEffects");
                });

            modelBuilder.Entity("WardenData.Models.SessionRunePrice", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer")
                        .HasColumnName("rune_id");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("SessionId", "RuneId");

                    b.HasIndex("RuneId")
                        .HasDatabaseName("ix_srp_rune");

                    b.ToTable("SessionRunePrices");
                });

            modelBuilder.Entity("WardenData.Models.OrderEffect", b =>
                {
                    b.HasOne("WardenData.Models.Effect", "Effect")
                        .WithMany("OrderEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_effects_effects");

                    b.HasOne("WardenData.Models.Order", "Order")
                        .WithMany("OrderEffects")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_effects_orders");

                    b.Navigation("Effect");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.HasOne("WardenData.Models.Rune", "Rune")
                        .WithMany("RuneHistories")
                        .HasForeignKey("RuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_histories_runes");

                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany("RuneHistories")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_histories_sessions");

                    b.Navigation("Rune");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistoryEffectChange", b =>
                {
                    b.HasOne("WardenData.Models.Effect", "Effect")
                        .WithMany("RuneHistoryEffectChanges")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_history_effect_changes_effects");

                    b.HasOne("WardenData.Models.RuneHistory", "RuneHistory")
                        .WithMany("RuneHistoryEffectChanges")
                        .HasForeignKey("RuneHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_history_effect_changes_rune_histories");

                    b.Navigation("Effect");

                    b.Navigation("RuneHistory");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.HasOne("WardenData.Models.Order", "Order")
                        .WithMany("Sessions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WardenData.Models.SessionInitialEffect", b =>
                {
                    b.HasOne("WardenData.Models.Effect", "Effect")
                        .WithMany("SessionInitialEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_initial_effects_effects");

                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany("SessionInitialEffects")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_initial_effects_sessions");

                    b.Navigation("Effect");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WardenData.Models.SessionRunePrice", b =>
                {
                    b.HasOne("WardenData.Models.Rune", "Rune")
                        .WithMany("SessionRunePrices")
                        .HasForeignKey("RuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_rune_prices_runes");

                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany("SessionRunePrices")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_rune_prices_sessions");

                    b.Navigation("Rune");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WardenData.Models.Effect", b =>
                {
                    b.Navigation("OrderEffects");

                    b.Navigation("RuneHistoryEffectChanges");

                    b.Navigation("SessionInitialEffects");
                });

            modelBuilder.Entity("WardenData.Models.Order", b =>
                {
                    b.Navigation("OrderEffects");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("WardenData.Models.Rune", b =>
                {
                    b.Navigation("RuneHistories");

                    b.Navigation("SessionRunePrices");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.Navigation("RuneHistoryEffectChanges");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.Navigation("RuneHistories");

                    b.Navigation("SessionInitialEffects");

                    b.Navigation("SessionRunePrices");
                });
#pragma warning restore 612, 618
        }
    }
}
