// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WardenData.Models;

#nullable disable

namespace WardenData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250920133101_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WardenData.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("ix_orders_user_name");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WardenData.Models.OrderEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("DesiredValue")
                        .HasColumnType("bigint")
                        .HasColumnName("desired_value");

                    b.Property<string>("EffectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect_name");

                    b.Property<long>("MaxValue")
                        .HasColumnType("bigint")
                        .HasColumnName("max_value");

                    b.Property<long>("MinValue")
                        .HasColumnType("bigint")
                        .HasColumnName("min_value");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderEffects");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasSucceed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_succeed");

                    b.Property<bool>("HasSynchronized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_synchronized");

                    b.Property<bool>("IsTenta")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tenta");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer")
                        .HasColumnName("rune_id");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("RuneHistories");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistoryEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.Property<string>("EffectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect_name");

                    b.Property<int>("RuneHistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("rune_history_id");

                    b.HasKey("Id");

                    b.HasIndex("RuneHistoryId");

                    b.ToTable("RuneHistoryEffects");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WardenData.Models.SessionEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.Property<string>("EffectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("effect_name");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionEffects");
                });

            modelBuilder.Entity("WardenData.Models.SessionRunePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("RuneId")
                        .HasColumnType("integer")
                        .HasColumnName("rune_id");

                    b.Property<string>("RuneName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rune_name");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionRunePrices");
                });

            modelBuilder.Entity("WardenData.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_users_token");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WardenData.Models.Order", b =>
                {
                    b.HasOne("WardenData.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WardenData.Models.OrderEffect", b =>
                {
                    b.HasOne("WardenData.Models.Order", "Order")
                        .WithMany("OrderEffects")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_effects_orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_histories_sessions");

                    b.HasOne("WardenData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_histories_users");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistoryEffect", b =>
                {
                    b.HasOne("WardenData.Models.RuneHistory", "RuneHistory")
                        .WithMany("RuneHistoryEffects")
                        .HasForeignKey("RuneHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rune_history_effects_rune_histories");

                    b.Navigation("RuneHistory");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.HasOne("WardenData.Models.Order", "Order")
                        .WithMany("Sessions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_orders");

                    b.HasOne("WardenData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WardenData.Models.SessionEffect", b =>
                {
                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany("SessionEffects")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_effects_sessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WardenData.Models.SessionRunePrice", b =>
                {
                    b.HasOne("WardenData.Models.Session", "Session")
                        .WithMany("SessionRunePrices")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_rune_prices_sessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WardenData.Models.Order", b =>
                {
                    b.Navigation("OrderEffects");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("WardenData.Models.RuneHistory", b =>
                {
                    b.Navigation("RuneHistoryEffects");
                });

            modelBuilder.Entity("WardenData.Models.Session", b =>
                {
                    b.Navigation("SessionEffects");

                    b.Navigation("SessionRunePrices");
                });

            modelBuilder.Entity("WardenData.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
